apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ template "zakenapi.name" . }}"
  namespace: "{{ template "zrc.namespace" . }}"
  labels:
    {{- include "zrc.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "zakenapi.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "zakenapi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: zakenapi
          image: {{ .Values.zakenapi.images.imageRepo}}:{{ .Values.zakenapi.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          ports:
            - containerPort: {{ .Values.zakenapi.service.port }}
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: zrc.conf.kubernetes
            - name: SECRET_KEY
              value: 8u9chcd4g1%i5z)u@s6#c#0u%s_gggx*915w(yzrf#awezmu^i
            - name: ZTC_JWT_SECRET
              value: dummy
            - name: ALLOWED_HOSTS
              value: {{ .Values.config.host }}
            - name: DB_NAME
              value: {{ .Values.database.name }}
            - name: DB_HOST
              value: "{{ template "postgres.serviceName" . }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ template "postgres.secretName" . }}"
                  key: {{ .Values.secret.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "postgres.secretName" . }}"
                  key: {{ .Values.secret.password }}
