apiVersion: v1
kind: Service
metadata:
  name:  "{{ template "zakenapi.serviceName" . }}"
  namespace: "{{ template "zrc.namespace" . }}"
spec:
  selector:
    {{- include "zakenapi.selectorLabels" . | nindent 8 }}
  ports:
    - name: "http"
      port: {{ .Values.zakenapi.service.port  }}
      targetPort: {{ .Values.zakenapi.service.port  }}
