language: python
cache: pip

python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts

env:
  global:
    - DJANGO_SETTINGS_MODULE=zrc.conf.ci
    - SECRET_KEY=dummy
    - DB_USER=postgres
    - DB_PASSWORD=
    - DEPLOYMENT=zrc
  matrix:
    - TOXENV=django_tests
    - TOXENV=isort
    - TOXENV=black

install:
  - pip install tox tox-travis

script: tox

jobs:
  include:
    # First stage is 'Tests' by default and populated from env matrix
    # expansion
    - stage: Docker images
      name: "Docker image build"
      before_install: skip
      install: skip
      before_script: skip
      script: docker build . --build-arg COMMIT_HASH=${TRAVIS_COMMIT:-`git rev-parse HEAD`}

    - stage: Publication
      name: Publish Docker image
      services:
        - docker
      after_success: echo "deploying..."
      deploy:
        - provider: script
          script: bash bin/cicd.sh latest yes
          on:
            branch: master

        - provider: script
          script: bash bin/cicd.sh $TRAVIS_TAG yes
          on:
            tags: true

after_success:
  - pip install codecov
  - codecov
