apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: "{{ template "zrc.namespace" . }}"
  labels:
    type: local
spec:
  storageClassName: "{{ include "postgres.storageClassName" . }}"
  capacity:
    storage: 25Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/pv0003/
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: "{{ template "zrc.namespace" . }}"
spec:
  storageClassName: "{{ template "postgres.storageClassName" . }}"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Mi
