apiVersion: v1
kind: Service
metadata:
  name:  "{{ template "postgres.serviceName" . }}"
  namespace: "{{ template "zrc.namespace" . }}"
spec:
  selector:
    {{- include "postgres.selectorLabels" . | nindent 8 }}
  ports:
    - name: "http"
      port: {{ .Values.postgres.service.port  }}
      targetPort: {{ .Values.postgres.service.port }}
