# Generated by Django 2.0.13 on 2019-05-02 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0056_auto_20190311_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('bron', models.CharField(max_length=3)),
                ('actie', models.CharField(max_length=20)),
                ('actieWeergave', models.CharField(blank=True, max_length=30)),
                ('resultaat', models.IntegerField()),
                ('hoofdObject', models.URLField()),
                ('resource', models.CharField(max_length=20)),
                ('resourceUrl', models.URLField()),
                ('aanmaakdatum', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
