# Generated by Django 2.0.13 on 2019-05-03 08:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0057_audittrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='versie_na',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='versie_voor',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
