# Generated by Django 2.0.13 on 2019-05-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0058_auto_20190503_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audittrail',
            old_name='versie_na',
            new_name='nieuw',
        ),
        migrations.RenameField(
            model_name='audittrail',
            old_name='versie_voor',
            new_name='oud',
        ),
    ]
