# Generated by Django 2.0.13 on 2019-05-03 13:54

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0059_auto_20190503_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='nieuw',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='oud',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
