# Generated by Django 2.2.2 on 2019-06-18 14:25

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0061_auto_20190617_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaak',
            name='relevante_andere_zaken',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True), blank=True, default=list, help_text='Een lijst van objecten met ieder twee elementen:\n* `zaak` - een url naar een andere `Zaak`\n* `aardRelatie` - beschrijving van de relatie tussen de twee `Zaak`en, waarbij de onderstaande waardes toegestaan zijn.', size=None),
        ),
    ]
