# Generated by Django 2.2.2 on 2019-06-13 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0062_auto_20190613_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestiging',
            name='handelsnaam',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, help_text='De naam van de vestiging waaronder gehandeld wordt.', max_length=625), size=None),
        ),
    ]
