# Generated by Django 2.2.2 on 2019-06-13 10:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0063_auto_20190613_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestiging',
            name='handelsnaam',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=625), default=list, help_text='De naam van de vestiging waaronder gehandeld wordt.', size=None),
        ),
    ]
