# Generated by Django 2.2.2 on 2019-06-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0064_copy_relevante_andere_zaken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaak',
            name='relevante_andere_zaken',
        ),
    ]
