# Generated by Django 2.2.2 on 2019-06-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0065_remove_zaak_relevante_andere_zaken'),
        ('datamodel', '0063_auto_20190620_1743'),
    ]

    operations = [
    ]
