# Generated by Django 2.2.2 on 2019-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("datamodel", "0082_normalize_enums")]

    operations = [
        migrations.AddField(
            model_name="status",
            name="_etag",
            field=models.CharField(
                default="",
                editable=False,
                help_text="MD5 hash of the resource representation in its current version.",
                max_length=32,
                verbose_name="etag value",
            ),
            preserve_default=False,
        )
    ]
