# Generated by Django 2.2.4 on 2019-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0083_status__etag'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultaat',
            name='_etag',
            field=models.CharField(default='', editable=False, help_text='MD5 hash of the resource representation in its current version.', max_length=32, verbose_name='etag value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='_etag',
            field=models.CharField(default='', editable=False, help_text='MD5 hash of the resource representation in its current version.', max_length=32, verbose_name='etag value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zaak',
            name='_etag',
            field=models.CharField(default='', editable=False, help_text='MD5 hash of the resource representation in its current version.', max_length=32, verbose_name='etag value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zaakeigenschap',
            name='_etag',
            field=models.CharField(default='', editable=False, help_text='MD5 hash of the resource representation in its current version.', max_length=32, verbose_name='etag value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zaakinformatieobject',
            name='_etag',
            field=models.CharField(default='', editable=False, help_text='MD5 hash of the resource representation in its current version.', max_length=32, verbose_name='etag value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zaakobject',
            name='_etag',
            field=models.CharField(default='', editable=False, help_text='MD5 hash of the resource representation in its current version.', max_length=32, verbose_name='etag value'),
            preserve_default=False,
        ),
    ]
