# Generated by Django 2.2.8 on 2020-09-04 09:46

from django.db import migrations
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0087_auto_20191202_1602"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaak",
            name="opdrachtgevende_organisatie",
            field=vng_api_common.fields.RSINField(
                blank=True,
                help_text="De krachtens publiekrecht ingestelde rechtspersoon dan wel ander niet-natuurlijk persoon waarbinnen het (bestuurs)orgaan zetelt dat opdracht heeft gegeven om taken uit te voeren waaraan de zaak invulling geeft.",
                max_length=9,
            ),
        ),
    ]
