# Generated by Django 2.2.19 on 2022-02-22 14:10

from django.db import migrations, models
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0089_zaakobject_object_type_overige_definitie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaak',
            name='gerelateerde_externe_zaken_aanvraagdatum',
            field=models.DateField(blank=True, help_text='De datum waarop verzocht is om de behandeling van de gerelateerde ZAAK uit te gaan voeren.', null=True, verbose_name='aanvraagdatum'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='gerelateerde_externe_zaken_aard_relatie',
            field=models.CharField(blank=True, choices=[('opdrachtgever', 'De gerelateerde zaak levert een bijdrage aan het bereiken van de uitkomst van de onderhanden zaak.'), ('opdrachtnemer', 'Aan het bereiken van de uitkomst van de gerelateerde zaak levert de onderhanden zaak een bijdrage.')], help_text='De datum waarop verzocht is om de behandeling van de gerelateerde ZAAK uit te gaan voeren.', max_length=14, verbose_name='aard relatie'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='gerelateerde_externe_zaken_datum_status_gezet',
            field=models.DateTimeField(blank=True, help_text='De datum waarop de gerelateerde ZAAK de laatst bekende status heeft verkregen.', null=True, verbose_name='datum status gezet'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='gerelateerde_externe_zaken_einddatum',
            field=models.DateField(blank=True, help_text='De datum waarop de uitvoering van de gerelateerde ZAAK afgerond is.', null=True, verbose_name='einddatum'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='gerelateerde_externe_zaken_resultaatomschrijving',
            field=models.CharField(blank=True, help_text='Een korte omschrijving wat het resultaat van de gerelateerde ZAAK inhoudt.', max_length=80, verbose_name='resultaatomschrijving'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='gerelateerde_externe_zaken_startdatum',
            field=models.DateField(blank=True, help_text='De datum waarop met de uitvoering van de gerelateerde ZAAK is gestart.', null=True, verbose_name='startdatum'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='gerelateerde_externe_zaken_status_omschrijving_generiek',
            field=models.CharField(blank=True, help_text='Algemeen gehanteerde omschrijving van de aard van de laatst bekende status van de gerelateerde ZAAK.', max_length=80, verbose_name='status-omschrijving generiek'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='gerelateerde_externe_zaken_url',
            field=models.URLField(blank=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='gerelateerde_externe_zaken_verantwoordelijke_organisatie',
            field=vng_api_common.fields.RSINField(blank=True, help_text='Het RSIN van de organisatie die verantwoordelijk is voor de behandeling van de gerelateerde ZAAK.', max_length=9, verbose_name='verantwoordelijke organisatie'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='gerelateerde_externe_zaken_zaakidentificatie',
            field=models.CharField(blank=True, help_text='De unieke identificatie van de gerelateerde ZAAK.', max_length=40, verbose_name='zaakidentificatie'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='gerelateerde_externe_zaken_zaaktype_omschrijving_generiek',
            field=models.CharField(blank=True, help_text='Algemeen gehanteerde omschrijving van de aard van ZAAKen van het ZAAKTYPE waartoe de gerelateerde zaak behoort.', max_length=80, verbose_name='zaaktype-omschrijving generiek'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='gerelateerde_externe_zaken_zaaktypecode',
            field=models.CharField(blank=True, help_text='De algemeen gehanteerde code van de aard van ZAAKen van het ZAAKTYPE waartoe de gerelateerde zaak behoort.', max_length=10, verbose_name='zaaktypecode'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='processobject_datumkenmerk',
            field=models.CharField(blank=True, help_text='De naam van de attribuutsoort van het procesobject dat bepalend is voor het einde van de procestermijn.', max_length=250, verbose_name='datumkenmerk'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='processobject_identificatie',
            field=models.CharField(blank=True, help_text='De unieke aanduiding van het procesobject.', max_length=250, verbose_name='identificatie'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='processobject_objecttype',
            field=models.CharField(blank=True, help_text='Het soort object dat het procesobject representeert.', max_length=250, verbose_name='objecttype'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='processobject_registratie',
            field=models.CharField(blank=True, help_text='De naam van de registratie waarvan het procesobject deel uit maakt.', max_length=250, verbose_name='registratie'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='processobjectaard',
            field=models.CharField(blank=True, help_text='Omschrijving van het object, subject of gebeurtenis waarop, vanuit archiveringsoptiek, de zaak betrekking heeft.', max_length=200, null=True, verbose_name='procesobjectaard'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='resultaattoelichting',
            field=models.TextField(blank=True, help_text='Een toelichting op wat het resultaat van de zaak inhoudt.', max_length=1000, verbose_name='resultaattoelichting'),
        ),
        migrations.AddField(
            model_name='zaak',
            name='startdatum_bewaartermijn',
            field=models.DateField(blank=True, help_text='De datum die de start markeert van de termijn waarop het zaakdossier vernietigd moet worden.', null=True, verbose_name='startdatum bewaartermijn'),
        ),
    ]
