# Generated by Django 2.2.19 on 2022-04-19 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0089_zaakobject_object_type_overige_definitie"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "tijdstip",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Het tijdstip waarop de STATUS de SUBSTATUS heeft verkregen.",
                    ),
                ),
                (
                    "omschrijving",
                    models.TextField(
                        help_text="Een, voor de initiator van de zaak relevante, toelichting op de substatus bij een hoofdstatus van een zaak.",
                        max_length=200,
                    ),
                ),
                (
                    "doelgroep",
                    models.CharField(
                        blank=True,
                        choices=[("betrokkenen", "betrokkenen"), ("intern", "Intern")],
                        db_index=True,
                        default="betrokkenen",
                        help_text="Indicatie van van de zichtbaarheid van een substatus.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        help_text="URL-referentie naar de hoofdSTATUS.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamodel.Status",
                    ),
                ),
                (
                    "zaak",
                    models.ForeignKey(
                        help_text="URL-referentie naar de ZAAK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamodel.Zaak",
                    ),
                ),
            ],
            options={
                "verbose_name": "substatus",
                "verbose_name_plural": "substatussen",
            },
        ),
    ]
