# Generated by Django 2.2.19 on 2022-03-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0090_auto_20220222_1410"),
    ]

    operations = [
        migrations.AddField(
            model_name="rol",
            name="afwijkende_naam_betrokkene",
            field=models.TextField(
                blank=True,
                help_text="De naam van de betrokkene waaronder deze in relatie tot de zaak aangesproken wil worden.",
                max_length=625,
                verbose_name="afwijkende naam betrokkene",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="contactpersoon_email",
            field=models.EmailField(
                blank=True,
                help_text="Elektronich postadres waaronder de contactpersoon in de regel bereikbaar is.",
                max_length=254,
                verbose_name="email",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="contactpersoon_functie",
            field=models.CharField(
                blank=True,
                help_text="De aanduiding van de taken, rechten en plichten die de contactpersoon heeft binnen de organisatie van BETROKKENE. ",
                max_length=50,
                verbose_name="functie",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="contactpersoon_naam",
            field=models.CharField(
                blank=True,
                help_text="De opgemaakte naam van de contactpersoon namens de BETROKKENE.",
                max_length=40,
                verbose_name="naam",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="contactpersoon_telefoonnummer",
            field=models.CharField(
                blank=True,
                help_text="Telefoonnummer waaronder de contactpersoon in de regel bereikbaar is.",
                max_length=20,
                verbose_name="telefoonnummer",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="statussen",
            field=models.ManyToManyField(
                blank=True,
                help_text="De BETROKKENE die in zijn/haar ROL in een ZAAK heeft geregistreerd dat STATUSsen in die ZAAK bereikt zijn.",
                related_name="rollen",
                to="datamodel.Status",
                verbose_name="statussen",
            ),
        ),
    ]
