# Generated by Django 2.2.19 on 2022-03-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0091_auto_20220308_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='gezetdoor',
            field=models.URLField(blank=True, help_text='De BETROKKENE die in zijn/haar ROL in een ZAAK heeft geregistreerd dat STATUSsen in die ZAAK bereikt zijn.', verbose_name='gezet door'),
        ),
        migrations.AddField(
            model_name='status',
            name='indicatie_laatst_gezette_status',
            field=models.BooleanField(default=False, help_text='Het gegeven is afleidbaar uit de historie van de attribuutsoort Datum status gezet van van alle statussen bij de desbetreffende zaak.', verbose_name='indicatie laatst gezette status'),
        ),
        migrations.AddField(
            model_name='status',
            name='zaakinformatieobjecten',
            field=models.ManyToManyField(blank=True, help_text='De bij de desbetreffende ZAAK behorende STATUS waarvoor het ZAAK-INFORMATIEOBJECT relevant is (geweest) met het oog op het bereiken van die STATUS en/of de communicatie daarover.', related_name='statussen', to='datamodel.ZaakInformatieObject', verbose_name='zaakinformatieobjecten'),
        ),
    ]
