# Generated by Django 2.2.19 on 2022-07-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datamodel", "0093_auto_20220531_1024"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zaak",
            name="gerelateerde_externe_zaken_aanvraagdatum",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="gerelateerde_externe_zaken_aard_relatie",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="gerelateerde_externe_zaken_datum_status_gezet",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="gerelateerde_externe_zaken_einddatum",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="gerelateerde_externe_zaken_resultaatomschrijving",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="gerelateerde_externe_zaken_startdatum",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="gerelateerde_externe_zaken_status_omschrijving_generiek",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="gerelateerde_externe_zaken_url",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="gerelateerde_externe_zaken_verantwoordelijke_organisatie",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="gerelateerde_externe_zaken_zaakidentificatie",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="gerelateerde_externe_zaken_zaaktype_omschrijving_generiek",
        ),
        migrations.RemoveField(
            model_name="zaak",
            name="gerelateerde_externe_zaken_zaaktypecode",
        ),
        migrations.AlterField(
            model_name="zaakobject",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("adres", "Adres"),
                    ("besluit", "Besluit"),
                    ("buurt", "Buurt"),
                    ("enkelvoudig_document", "Enkelvoudig document"),
                    ("gemeente", "Gemeente"),
                    ("gemeentelijke_openbare_ruimte", "Gemeentelijke openbare ruimte"),
                    ("huishouden", "Huishouden"),
                    ("inrichtingselement", "Inrichtingselement"),
                    ("kadastrale_onroerende_zaak", "Kadastrale onroerende zaak"),
                    ("kunstwerkdeel", "Kunstwerkdeel"),
                    ("maatschappelijke_activiteit", "Maatschappelijke activiteit"),
                    ("medewerker", "Medewerker"),
                    ("natuurlijk_persoon", "Natuurlijk persoon"),
                    ("niet_natuurlijk_persoon", "Niet-natuurlijk persoon"),
                    ("openbare_ruimte", "Openbare ruimte"),
                    ("organisatorische_eenheid", "Organisatorische eenheid"),
                    ("pand", "Pand"),
                    ("spoorbaandeel", "Spoorbaandeel"),
                    ("status", "Status"),
                    ("terreindeel", "Terreindeel"),
                    ("terrein_gebouwd_object", "Terrein gebouwd object"),
                    ("vestiging", "Vestiging"),
                    ("waterdeel", "Waterdeel"),
                    ("wegdeel", "Wegdeel"),
                    ("wijk", "Wijk"),
                    ("woonplaats", "Woonplaats"),
                    ("woz_deelobject", "Woz deel object"),
                    ("woz_object", "Woz object"),
                    ("woz_waarde", "Woz waarde"),
                    ("zakelijk_recht", "Zakelijk recht"),
                    ("overige", "Overige"),
                ],
                help_text="Beschrijft het type OBJECT gerelateerd aan de ZAAK. Als er geen passend type is, dan moet het type worden opgegeven onder `objectTypeOverige`.",
                max_length=100,
            ),
        ),
    ]
