# Generated by Django 3.2.14 on 2022-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0095_auto_20220927_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="vestiging",
            name="kvk_nummer",
            field=models.CharField(
                blank=True,
                help_text="Een uniek nummer gekoppeld aan de onderneming.",
                max_length=8,
            ),
        ),
    ]
