# Generated by Django 3.2.14 on 2022-11-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0095_auto_20220927_1502"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="indicatie_laatst_gezette_status",
        ),
    ]
