# Generated by Django 3.2.14 on 2023-02-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datamodel", "0097_vestiging_kvk_nummer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rol",
            name="contactpersoon_naam",
            field=models.CharField(
                blank=True,
                help_text="De opgemaakte naam van de contactpersoon namens de BETROKKENE.",
                max_length=200,
                verbose_name="naam",
            ),
        ),
    ]
