# Generated by Django 3.2.14 on 2023-09-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0097_vestiging_kvk_nummer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaak',
            name='resultaattoelichting',
        ),
    ]
