# Generated by Django 3.2.14 on 2023-09-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0098_alter_rol_contactpersoon_naam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zaak",
            name="resultaattoelichting",
        ),
    ]
