apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
  labels:
    env: test
    app: postgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
        release: 14-master
      annotations:
        app: postgis
        env: test
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:14-master
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgis-pgdata
      volumes:
        - name: postgis-pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc
